# .github/workflows/jenkins-pipeline.yml
name: Jenkins Pipeline Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jenkins-pipeline:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@master
        - name: jenkinsfile-runner-prepackaged
          uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
