name: Jenkins single-shot master
on: push

jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Jenkinsfile Runner
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
        with:
          jenkinsfile: Jenkinsfile       
          pluginstxt: plugins.txt        
          command: run                   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
